# Generated by Django 6.0.5 on 2026-06-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0002_dojo_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='andesc',
            field=models.CharField(default='new dojo'),
        ),
    ]
